name       : deathcrush-lv2
version    : 04.10
release    : 1
source     :
    - http://downloads.sourceforge.net/project/intonarumori/Deathcrush/DeathcrushLV2-04.10.tar.bz2 : d94c03688fe4bdd2471c7370941f55cd93f77c0641f902441cb0e3b521f2037a
license    : GPL-3.0
component  : multimedia.audio
summary    : Deathcrush is an LV2 distorsion plugin.
description: |
    Deathcrush is an LV2 distorsion plugin, made up of some raw effects (such as bitcrusher and compressor) to really ruin your gentle sounds.
build      : |
    pushd src/
    %make
install    : |
    plugindir=${installdir}%libdir%/lv2/deathcrush.lv2
    pushd src/
    install -dm00644 $plugindir
    mv deathcrush.lv2/* $plugindir/
